<?php

namespace AppBundle\Repository;

/**
 * ChatStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
