<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findOperators(): array
    {
        $query = 'SELECT id, name FROM "user" u WHERE CAST(u.roles AS text) LIKE :role';

        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute(['role' => '%ROLE_OPERATOR%']);

        return $stmt->fetchAll();
    }
}
