# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  app.security.authentication_success_handler:
    class: AppBundle\Security\CustomLoginSuccessHandler
    arguments: ["@router"]
  app.chat_service:
    class: AppBundle\Service\ChatService
    arguments:
      - '@doctrine.orm.entity_manager'
  app.chat_controller:
    class: AppBundle\Controller\ChatController
    arguments:
      - '@app.chat_service'
      - '@templating'
    public: true